### ISSUE TITLE
[服务端通知] 自动发送邮件

### ISSUE THREAD

**Issue by StarPixel-Team** [StarPixel-Team/Website#3]
### 检查项

- [X] 我已在 15 分钟内刷新了网站，且未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/StarPixel-Team/Website/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/StarPixel-Team/Website/discussions/categories/%E6%96%B0%E5%8A%9F%E8%83%BD%E6%8F%90%E6%A1%88)，确认了这一提案未在投票列表中。

### 描述

此 Issue 为邮件 API。

### 原因

此 Issue 为邮件 API。

**Comment by youzi-2333** [comment]
测试一波……
